# Generated by Django 4.0.1 on 2022-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='Task name')),
                ('status', models.CharField(choices=[('U', 'Not yet Started'), ('O', 'ONGOING'), ('D', 'DONE')], max_length=10, verbose_name='Task status')),
            ],
        ),
    ]
